# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('locked', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('deadline', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('length', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='possible_times',
            field=models.ManyToManyField(to='api.TimeInterval'),
        ),
    ]
