# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171124_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='possible_times',
            field=models.ManyToManyField(blank=True, to='api.TimeInterval'),
        ),
    ]
